//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SessionOne
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataAnalyzator
    {
        public int Id { get; set; }
        public Nullable<int> Name { get; set; }
        public System.DateTime DateTimeOrder { get; set; }
        public System.DateTime DateRunTime { get; set; }
    
        public virtual Analyzers Analyzers { get; set; }
    }
}
