//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SessionOne
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int Id { get; set; }
        public DateTime DateCreate { get; set; }
        public Nullable<int> PacientId { get; set; }
        public Nullable<int> Services { get; set; }
        public string StatusOrder { get; set; }
        public string StatusService { get; set; }
        public Nullable<int> TimeDay { get; set; }
        public string Result { get; set; }
        public Nullable<double> Price { get; set; }
        public string Comment { get; set; }
    
        public virtual Pacients Pacients { get; set; }
        public virtual Services Services1 { get; set; }
    }
}
