//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SessionOne
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersArchive
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<int> PacientId { get; set; }
        public string Services { get; set; }
        public string StatusOrder { get; set; }
        public string StatusService { get; set; }
        public Nullable<int> TimeDay { get; set; }
    }
}
