//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SessionOne
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuccessService
    {
        public int Id { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<int> LoginId { get; set; }
        public Nullable<int> Analyzator { get; set; }
    
        public virtual Analyzers Analyzers { get; set; }
        public virtual Services Services { get; set; }
        public virtual Users Users { get; set; }
    }
}
